#!/bin/sh

usage() {
	cat <<- EOF
	wetter [ -h | --help | --no-proxy --lang <it|de|..> ] <Town>|~<Place>

	Get weather from wttr.in for <Town> or <Place>
	EOF
}

LNG=`echo "$LANG" | grep -o "^.."`
NOPROXY=""
while [ "$1" ]; do
	case "$1" in
		--help|-h)
			usage
			exit 0
			;;
		--no-proxy)
			NOPROXY="--no-proxy"
			;;
		--lang)
			shift
			LNG="$1"
			;;
		-*)
			echo "Unknown arg: $1" >&2
			exit 1
			;;
		*)
			break
			;;
	esac
	shift
done

[ "$LNG" != "" ] && EXTRA="lang=$LNG&"
EXTRA="${EXTRA}m"

CANONICAL=`echo "$@" | sed 's/~/+/g'`
wget $NOPROXY -q  -O - "wttr.in/${CANONICAL}?${EXTRA}"
