#!/bin/sh

usage() {
	cat <<- EOF
	wetter [ -h | --help | --no-proxy --lang <it|de|..> ] <Town>

	Get weather from wttr.in for <Town>
	EOF
}

LNG=`echo "$LANG" | grep -o "^.."`
NOPROXY=""
while [ "$1" ]; do
	case "$1" in
		--help|-h)
			usage
			;;
		--no-proxy)
			NOPROXY="--no-proxy"
			;;
		--lang)
			shift
			LNG="$1"
			;;
		-*)
			echo "Unknown arg: $1" >&2
			exit 1
			;;
		*)
			break
			;;
	esac
	shift
done

EXTRA="m"
[ "$LNG" != "" ] && EXTRA="lang=$LNG"
wget $NOPROXY -q  -O - wttr.in/$1?${EXTRA}
