#!/bin/sh

usage() {
	cat <<- EOF
	wetter [ -h | --help | --no-proxy --lang <it|de|..> ] <Town>|~<Place>

	Get weather from wttr.in for <Town> or <Place>
	EOF
}

LNG="${LANG%_*}"
NOPROXY=""
while [ "$1" ]; do
	case "$1" in
		--help|-h)
			usage
			exit 0
			;;
		--no-proxy)
			NOPROXY="--no-proxy"
			;;
		--lang)
			shift
			LNG="$1"
			;;
		-*)
			echo "Unknown arg: $1" >&2
			exit 1
			;;
		*)
			break
			;;
	esac
	shift
done

EXTRA="m"
[ "$LNG" != "" ] && EXTRA="${EXTRA}&lang=$LNG"

# Number of columns <125 => choos narrow layout
COLUMNS=`tput cols`
[ "$COLUMNS" -lt 125 ] && EXTRA="${EXTRA}&n"

CANONICAL=`echo "$@" | sed 's/ /+/g'`
wget $NOPROXY -q  -O - "wttr.in/${CANONICAL}?${EXTRA}"
